version: 2
updates:
  # Verificar atualizações para Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "gabrielmaia"
    commit-message:
      prefix: "cargo"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    ignore:
      # Ignorar atualizações de versões principais que podem introduzir quebras
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  # Verificar atualizações para GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "gabrielmaia"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"