name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            artifact_name: winx
            asset_name: winx-linux-amd64
          - os: macos-latest
            artifact_name: winx
            asset_name: winx-macos-amd64
          - os: windows-latest
            artifact_name: winx.exe
            asset_name: winx-windows-amd64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release --bin winx_openai

      - name: Rename binary
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/release/winx_openai.exe ${{ matrix.artifact_name }}
          else
            cp target/release/winx_openai ${{ matrix.artifact_name }}
          fi

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact_name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}